/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Analysis = IDL.Record({
  'id' : IDL.Nat,
  'provider' : IDL.Text,
  'analysisType' : IDL.Text,
  'createdAt' : IDL.Int,
  'bookId' : IDL.Nat,
  'chapterId' : IDL.Opt(IDL.Nat),
  'resultContent' : IDL.Text,
});
export const TextAnnotation = IDL.Record({
  'id' : IDL.Nat,
  'alternativeProposal' : IDL.Opt(IDL.Text),
  'explanation' : IDL.Text,
  'color' : IDL.Text,
  'text' : IDL.Text,
  'approved' : IDL.Bool,
  'analysisId' : IDL.Nat,
  'proposal' : IDL.Text,
});
export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'authorSummary' : IDL.Text,
  'characters' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'themes' : IDL.Text,
  'keyContext' : IDL.Text,
  'category' : IDL.Text,
  'ageCategory' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'charCount' : IDL.Nat,
  'title' : IDL.Text,
  'indentFirstLine' : IDL.Nat,
  'content' : IDL.Text,
  'indentRight' : IDL.Nat,
  'wordCount' : IDL.Nat,
  'indentLeft' : IDL.Nat,
  'createdAt' : IDL.Int,
  'bookId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'sessionId' : IDL.Text,
  'orderIndex' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'provider' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'bookId' : IDL.Nat,
  'sessionId' : IDL.Text,
});
export const ChatSessionMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'sessionId' : IDL.Nat,
});
export const ChatSession = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'chapterId' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'chapterId' : IDL.Nat,
  'anchorText' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'code' : IDL.Text,
  'usedAt' : IDL.Opt(IDL.Int),
  'usedBy' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
});
export const Recording = IDL.Record({
  'id' : IDL.Nat,
  'voice' : IDL.Text,
  'createdAt' : IDL.Int,
  'audioData' : IDL.Vec(IDL.Nat8),
  'bookId' : IDL.Nat,
  'chapterId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '__adminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  '__analyses' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Analysis))],
      ['query'],
    ),
  '__annotations' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TextAnnotation))],
      ['query'],
    ),
  '__books' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Book))],
      ['query'],
    ),
  '__chapters' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Chapter))],
      ['query'],
    ),
  '__chatMessages' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ChatMessage))],
      ['query'],
    ),
  '__chatSessionMessages' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ChatSessionMessage))],
      ['query'],
    ),
  '__chatSessions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ChatSession))],
      ['query'],
    ),
  '__comments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Comment))],
      ['query'],
    ),
  '__inviteCodes' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, InviteCode))],
      ['query'],
    ),
  '__nextAnalysisId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextAnnotationId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextBookId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextChapterId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextChatMessageId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextChatSessionId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextChatSessionMessageId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextCommentId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextRecordingId' : IDL.Func([], [IDL.Nat], ['query']),
  '__recordings' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Recording))],
      ['query'],
    ),
  'addChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'checkAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'clearChat' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'createBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createChapter' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createChatSession' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteAnalysis' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChatSession' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteRecording' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAnalysis' : IDL.Func([IDL.Nat], [IDL.Opt(Analysis)], []),
  'getAnnotation' : IDL.Func([IDL.Nat], [IDL.Opt(TextAnnotation)], []),
  'getAnnotations' : IDL.Func([IDL.Nat], [IDL.Vec(TextAnnotation)], []),
  'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], []),
  'getBookStats' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'totalChars' : IDL.Nat,
          'avgWordsPerChapter' : IDL.Nat,
          'chapterCount' : IDL.Nat,
          'totalWords' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], []),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatSessionMessage)], []),
  'getChatSessionsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(ChatSession)], []),
  'getOverallStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalBooks' : IDL.Nat,
          'totalChapters' : IDL.Nat,
          'totalWords' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getRecordingAudio' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
  'listAnalysesByBook' : IDL.Func([IDL.Nat], [IDL.Vec(Analysis)], []),
  'listAnalysesByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Analysis)], []),
  'listAnnotationsByAnalysis' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TextAnnotation)],
      [],
    ),
  'listBooksByOwner' : IDL.Func([], [IDL.Vec(Book)], []),
  'listChaptersByBook' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], []),
  'listCommentsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], []),
  'listInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], []),
  'listMessagesByBook' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(ChatMessage)],
      [],
    ),
  'listRecordingsByChapter' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'voice' : IDL.Text,
            'createdAt' : IDL.Int,
          })
        ),
      ],
      [],
    ),
  'reorderChapters' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
  'saveAnalysis' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveAnnotations' : IDL.Func(
      [
        IDL.Nat,
        IDL.Vec(
          IDL.Record({
            'alternativeProposal' : IDL.Opt(IDL.Text),
            'explanation' : IDL.Text,
            'color' : IDL.Text,
            'text' : IDL.Text,
            'proposal' : IDL.Text,
          })
        ),
      ],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'saveRecording' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'synthesizeSpeech' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Nat8)],
      [],
    ),
  'ttsTransform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'updateAnnotationApproved' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'updateBook' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateBookCharacters' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateBookMetadata' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateChapterIndents' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Analysis = IDL.Record({
    'id' : IDL.Nat,
    'provider' : IDL.Text,
    'analysisType' : IDL.Text,
    'createdAt' : IDL.Int,
    'bookId' : IDL.Nat,
    'chapterId' : IDL.Opt(IDL.Nat),
    'resultContent' : IDL.Text,
  });
  const TextAnnotation = IDL.Record({
    'id' : IDL.Nat,
    'alternativeProposal' : IDL.Opt(IDL.Text),
    'explanation' : IDL.Text,
    'color' : IDL.Text,
    'text' : IDL.Text,
    'approved' : IDL.Bool,
    'analysisId' : IDL.Nat,
    'proposal' : IDL.Text,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'authorSummary' : IDL.Text,
    'characters' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'themes' : IDL.Text,
    'keyContext' : IDL.Text,
    'category' : IDL.Text,
    'ageCategory' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'charCount' : IDL.Nat,
    'title' : IDL.Text,
    'indentFirstLine' : IDL.Nat,
    'content' : IDL.Text,
    'indentRight' : IDL.Nat,
    'wordCount' : IDL.Nat,
    'indentLeft' : IDL.Nat,
    'createdAt' : IDL.Int,
    'bookId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'sessionId' : IDL.Text,
    'orderIndex' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'provider' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'bookId' : IDL.Nat,
    'sessionId' : IDL.Text,
  });
  const ChatSessionMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'sessionId' : IDL.Nat,
  });
  const ChatSession = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'chapterId' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'chapterId' : IDL.Nat,
    'anchorText' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'code' : IDL.Text,
    'usedAt' : IDL.Opt(IDL.Int),
    'usedBy' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
  });
  const Recording = IDL.Record({
    'id' : IDL.Nat,
    'voice' : IDL.Text,
    'createdAt' : IDL.Int,
    'audioData' : IDL.Vec(IDL.Nat8),
    'bookId' : IDL.Nat,
    'chapterId' : IDL.Nat,
  });
  
  return IDL.Service({
    '__adminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    '__analyses' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Analysis))],
        ['query'],
      ),
    '__annotations' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TextAnnotation))],
        ['query'],
      ),
    '__books' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Book))],
        ['query'],
      ),
    '__chapters' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Chapter))],
        ['query'],
      ),
    '__chatMessages' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ChatMessage))],
        ['query'],
      ),
    '__chatSessionMessages' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ChatSessionMessage))],
        ['query'],
      ),
    '__chatSessions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ChatSession))],
        ['query'],
      ),
    '__comments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Comment))],
        ['query'],
      ),
    '__inviteCodes' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, InviteCode))],
        ['query'],
      ),
    '__nextAnalysisId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextAnnotationId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextBookId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextChapterId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextChatMessageId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextChatSessionId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextChatSessionMessageId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextCommentId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextRecordingId' : IDL.Func([], [IDL.Nat], ['query']),
    '__recordings' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Recording))],
        ['query'],
      ),
    'addChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'checkAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'clearChat' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'createBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createChapter' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createChatSession' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteAnalysis' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChatSession' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteRecording' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAnalysis' : IDL.Func([IDL.Nat], [IDL.Opt(Analysis)], []),
    'getAnnotation' : IDL.Func([IDL.Nat], [IDL.Opt(TextAnnotation)], []),
    'getAnnotations' : IDL.Func([IDL.Nat], [IDL.Vec(TextAnnotation)], []),
    'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], []),
    'getBookStats' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'totalChars' : IDL.Nat,
            'avgWordsPerChapter' : IDL.Nat,
            'chapterCount' : IDL.Nat,
            'totalWords' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], []),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatSessionMessage)], []),
    'getChatSessionsByChapter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatSession)],
        [],
      ),
    'getOverallStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalBooks' : IDL.Nat,
            'totalChapters' : IDL.Nat,
            'totalWords' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getRecordingAudio' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
    'listAnalysesByBook' : IDL.Func([IDL.Nat], [IDL.Vec(Analysis)], []),
    'listAnalysesByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Analysis)], []),
    'listAnnotationsByAnalysis' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TextAnnotation)],
        [],
      ),
    'listBooksByOwner' : IDL.Func([], [IDL.Vec(Book)], []),
    'listChaptersByBook' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], []),
    'listCommentsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], []),
    'listInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], []),
    'listMessagesByBook' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(ChatMessage)],
        [],
      ),
    'listRecordingsByChapter' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'voice' : IDL.Text,
              'createdAt' : IDL.Int,
            })
          ),
        ],
        [],
      ),
    'reorderChapters' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
    'saveAnalysis' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveAnnotations' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(
            IDL.Record({
              'alternativeProposal' : IDL.Opt(IDL.Text),
              'explanation' : IDL.Text,
              'color' : IDL.Text,
              'text' : IDL.Text,
              'proposal' : IDL.Text,
            })
          ),
        ],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'saveRecording' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'synthesizeSpeech' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Nat8)],
        [],
      ),
    'ttsTransform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'updateAnnotationApproved' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'updateBook' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateBookCharacters' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateBookMetadata' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateChapterIndents' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };