/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessCheckResult = { 'ExistingUser' : null } |
  { 'Admin' : null } |
  { 'NewUserNeedsCode' : null };
export interface Analysis {
  'id' : bigint,
  'provider' : string,
  'analysisType' : string,
  'createdAt' : bigint,
  'bookId' : bigint,
  'chapterId' : [] | [bigint],
  'resultContent' : string,
}
export interface Book {
  'id' : bigint,
  'title' : string,
  'ownerId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'category' : string,
}
export interface Chapter {
  'id' : bigint,
  'charCount' : bigint,
  'title' : string,
  'indentFirstLine' : bigint,
  'content' : string,
  'indentRight' : bigint,
  'wordCount' : bigint,
  'indentLeft' : bigint,
  'createdAt' : bigint,
  'bookId' : bigint,
  'updatedAt' : bigint,
  'orderIndex' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'provider' : string,
  'createdAt' : bigint,
  'role' : string,
  'bookId' : bigint,
}
export interface Comment {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'chapterId' : bigint,
  'anchorText' : string,
}
export interface InviteCode {
  'status' : InviteCodeStatus,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'createdAt' : bigint,
  'usedCount' : bigint,
  'claimedBy' : Array<Principal>,
  'maxUses' : bigint,
}
export type InviteCodeStatus = { 'active' : null } |
  { 'revoked' : null } |
  { 'exhausted' : null };
export interface Recording {
  'id' : bigint,
  'voice' : string,
  'createdAt' : bigint,
  'audioData' : Uint8Array,
  'bookId' : bigint,
  'chapterId' : bigint,
}
export interface TextAnnotation {
  'id' : bigint,
  'explanation' : string,
  'color' : string,
  'text' : string,
  'approved' : boolean,
  'analysisId' : bigint,
  'proposal' : string,
}
export interface _SERVICE {
  '__analyses' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Analysis]>
  >,
  '__annotations' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, TextAnnotation]>
  >,
  '__books' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Book]>
  >,
  '__chapters' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Chapter]>
  >,
  '__chatMessages' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, ChatMessage]>
  >,
  '__comments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Comment]>
  >,
  '__inviteCodes' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, InviteCode]>
  >,
  '__nextAnalysisId' : ActorMethod<[], bigint>,
  '__nextAnnotationId' : ActorMethod<[], bigint>,
  '__nextBookId' : ActorMethod<[], bigint>,
  '__nextChapterId' : ActorMethod<[], bigint>,
  '__nextChatMessageId' : ActorMethod<[], bigint>,
  '__nextCommentId' : ActorMethod<[], bigint>,
  '__nextInviteCodeId' : ActorMethod<[], bigint>,
  '__nextRecordingId' : ActorMethod<[], bigint>,
  '__recordings' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Recording]>
  >,
  'checkAccess' : ActorMethod<[], AccessCheckResult>,
  'claimInviteCode' : ActorMethod<[string], boolean>,
  'clearChat' : ActorMethod<[bigint], boolean>,
  'createBook' : ActorMethod<[string, string, string], bigint>,
  'createChapter' : ActorMethod<[bigint, string], bigint>,
  'createComment' : ActorMethod<[bigint, string, string], bigint>,
  'deleteAnalysis' : ActorMethod<[bigint], boolean>,
  'deleteBook' : ActorMethod<[bigint], boolean>,
  'deleteChapter' : ActorMethod<[bigint], boolean>,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'deleteMessage' : ActorMethod<[bigint], boolean>,
  'deleteRecording' : ActorMethod<[bigint], boolean>,
  'generateInviteCode' : ActorMethod<[bigint, [] | [bigint]], string>,
  'getAnalysis' : ActorMethod<[bigint], [] | [Analysis]>,
  'getAnnotation' : ActorMethod<[bigint], [] | [TextAnnotation]>,
  'getAnnotations' : ActorMethod<[bigint], Array<TextAnnotation>>,
  'getBook' : ActorMethod<[bigint], [] | [Book]>,
  'getBookStats' : ActorMethod<
    [bigint],
    {
      'totalChars' : bigint,
      'avgWordsPerChapter' : bigint,
      'chapterCount' : bigint,
      'totalWords' : bigint,
    }
  >,
  'getChapter' : ActorMethod<[bigint], [] | [Chapter]>,
  'getOverallStats' : ActorMethod<
    [],
    { 'totalBooks' : bigint, 'totalChapters' : bigint, 'totalWords' : bigint }
  >,
  'getRecordingAudio' : ActorMethod<[bigint], [] | [Uint8Array]>,
  'listAnalysesByBook' : ActorMethod<[bigint], Array<Analysis>>,
  'listAnalysesByChapter' : ActorMethod<[bigint], Array<Analysis>>,
  'listAnnotationsByAnalysis' : ActorMethod<[bigint], Array<TextAnnotation>>,
  'listBooksByOwner' : ActorMethod<[], Array<Book>>,
  'listChaptersByBook' : ActorMethod<[bigint], Array<Chapter>>,
  'listCommentsByChapter' : ActorMethod<[bigint], Array<Comment>>,
  'listInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'listMessagesByBook' : ActorMethod<[bigint], Array<ChatMessage>>,
  'listRecordingsByChapter' : ActorMethod<
    [bigint],
    Array<{ 'id' : bigint, 'voice' : string, 'createdAt' : bigint }>
  >,
  'reorderChapters' : ActorMethod<[bigint, Array<bigint>], boolean>,
  'revokeInviteCode' : ActorMethod<[string], boolean>,
  'saveAnalysis' : ActorMethod<
    [bigint, [] | [bigint], string, string, string],
    bigint
  >,
  'saveAnnotations' : ActorMethod<
    [
      bigint,
      Array<
        {
          'explanation' : string,
          'color' : string,
          'text' : string,
          'proposal' : string,
        }
      >,
    ],
    Array<bigint>
  >,
  'saveRecording' : ActorMethod<[bigint, bigint, string, Uint8Array], bigint>,
  'sendMessage' : ActorMethod<[bigint, string, string, string], bigint>,
  'updateAnnotationApproved' : ActorMethod<[bigint, boolean], boolean>,
  'updateBook' : ActorMethod<[bigint, string, string, string], boolean>,
  'updateChapter' : ActorMethod<[bigint, string, string], boolean>,
  'updateChapterIndents' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];