/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Comment {
    id: bigint;
    content: string;
    createdAt: bigint;
    chapterId: bigint;
    anchorText: string;
}
export interface Analysis {
    id: bigint;
    provider: string;
    analysisType: string;
    createdAt: bigint;
    bookId: bigint;
    chapterId?: bigint;
    resultContent: string;
}
export interface Book {
    id: bigint;
    writingStyle: string;
    title: string;
    ownerId: Principal;
    authorSummary: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    themes: string;
    keyContext: string;
    category: string;
    ageCategory: string;
}
export interface TextAnnotation {
    id: bigint;
    explanation: string;
    color: string;
    text: string;
    approved: boolean;
    analysisId: bigint;
    proposal: string;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    provider: string;
    createdAt: bigint;
    role: string;
    bookId: bigint;
}
export interface Chapter {
    id: bigint;
    charCount: bigint;
    title: string;
    indentFirstLine: bigint;
    content: string;
    indentRight: bigint;
    wordCount: bigint;
    indentLeft: bigint;
    createdAt: bigint;
    bookId: bigint;
    updatedAt: bigint;
    orderIndex: bigint;
}
export interface InviteCode {
    status: InviteCodeStatus;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    usedCount: bigint;
    claimedBy: Array<Principal>;
    maxUses: bigint;
}
export interface Recording {
    id: bigint;
    voice: string;
    createdAt: bigint;
    audioData: Uint8Array;
    bookId: bigint;
    chapterId: bigint;
}
export enum AccessCheckResult {
    ExistingUser = "ExistingUser",
    Admin = "Admin",
    NewUserNeedsCode = "NewUserNeedsCode"
}
export enum InviteCodeStatus {
    active = "active",
    revoked = "revoked",
    exhausted = "exhausted"
}
export interface backendInterface {
    __analyses(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Analysis]>>;
    __annotations(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, TextAnnotation]>>;
    __books(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Book]>>;
    __chapters(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Chapter]>>;
    __chatMessages(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, ChatMessage]>>;
    __comments(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Comment]>>;
    __inviteCodes(ko: string | null, count: bigint | null): Promise<Array<[string, InviteCode]>>;
    __nextAnalysisId(): Promise<bigint>;
    __nextAnnotationId(): Promise<bigint>;
    __nextBookId(): Promise<bigint>;
    __nextChapterId(): Promise<bigint>;
    __nextChatMessageId(): Promise<bigint>;
    __nextCommentId(): Promise<bigint>;
    __nextInviteCodeId(): Promise<bigint>;
    __nextRecordingId(): Promise<bigint>;
    __recordings(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Recording]>>;
    checkAccess(): Promise<AccessCheckResult>;
    claimInviteCode(code: string): Promise<boolean>;
    clearChat(bookId: bigint): Promise<boolean>;
    createBook(title: string, description: string, category: string): Promise<bigint>;
    createChapter(bookId: bigint, title: string): Promise<bigint>;
    createComment(chapterId: bigint, anchorText: string, content: string): Promise<bigint>;
    deleteAnalysis(id: bigint): Promise<boolean>;
    deleteBook(id: bigint): Promise<boolean>;
    deleteChapter(id: bigint): Promise<boolean>;
    deleteComment(id: bigint): Promise<boolean>;
    deleteMessage(id: bigint): Promise<boolean>;
    deleteRecording(id: bigint): Promise<boolean>;
    generateInviteCode(maxUses: bigint, expiresAt: bigint | null): Promise<string>;
    getAnalysis(id: bigint): Promise<Analysis | null>;
    getAnnotation(id: bigint): Promise<TextAnnotation | null>;
    getAnnotations(analysisId: bigint): Promise<Array<TextAnnotation>>;
    getBook(id: bigint): Promise<Book | null>;
    getBookStats(bookId: bigint): Promise<{
        totalChars: bigint;
        avgWordsPerChapter: bigint;
        chapterCount: bigint;
        totalWords: bigint;
    }>;
    getChapter(id: bigint): Promise<Chapter | null>;
    getOverallStats(): Promise<{
        totalBooks: bigint;
        totalChapters: bigint;
        totalWords: bigint;
    }>;
    getRecordingAudio(id: bigint): Promise<Uint8Array | null>;
    listAnalysesByBook(bookId: bigint): Promise<Array<Analysis>>;
    listAnalysesByChapter(chapterId: bigint): Promise<Array<Analysis>>;
    listAnnotationsByAnalysis(analysisId: bigint): Promise<Array<TextAnnotation>>;
    listBooksByOwner(): Promise<Array<Book>>;
    listChaptersByBook(bookId: bigint): Promise<Array<Chapter>>;
    listCommentsByChapter(chapterId: bigint): Promise<Array<Comment>>;
    listInviteCodes(): Promise<Array<InviteCode>>;
    listMessagesByBook(bookId: bigint): Promise<Array<ChatMessage>>;
    listRecordingsByChapter(chapterId: bigint): Promise<Array<{
        id: bigint;
        voice: string;
        createdAt: bigint;
    }>>;
    reorderChapters(bookId: bigint, orderedIds: Array<bigint>): Promise<boolean>;
    revokeInviteCode(code: string): Promise<boolean>;
    saveAnalysis(bookId: bigint, chapterId: bigint | null, analysisType: string, provider: string, resultContent: string): Promise<bigint>;
    saveAnnotations(analysisId: bigint, annotationData: Array<{
        explanation: string;
        color: string;
        text: string;
        proposal: string;
    }>): Promise<Array<bigint>>;
    saveRecording(chapterId: bigint, bookId: bigint, voice: string, audioData: Uint8Array): Promise<bigint>;
    sendMessage(bookId: bigint, role: string, content: string, provider: string): Promise<bigint>;
    updateAnnotationApproved(id: bigint, approved: boolean): Promise<boolean>;
    updateBook(id: bigint, title: string, description: string, category: string): Promise<boolean>;
    updateBookMetadata(id: bigint, ageCategory: string, authorSummary: string, keyContext: string, themes: string, writingStyle: string): Promise<boolean>;
    updateChapter(id: bigint, title: string, content: string): Promise<boolean>;
    updateChapterIndents(id: bigint, indentLeft: bigint, indentRight: bigint, indentFirstLine: bigint): Promise<boolean>;
}
import type { AccessCheckResult as _AccessCheckResult, Analysis as _Analysis, Book as _Book, Chapter as _Chapter, InviteCode as _InviteCode, InviteCodeStatus as _InviteCodeStatus, TextAnnotation as _TextAnnotation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __analyses(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Analysis]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__analyses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__analyses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __annotations(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, TextAnnotation]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__annotations(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__annotations(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __books(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Book]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__books(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__books(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __chapters(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Chapter]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__chapters(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chapters(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __chatMessages(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, ChatMessage]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__chatMessages(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chatMessages(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __comments(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Comment]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__comments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__comments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __inviteCodes(arg0: string | null, arg1: bigint | null): Promise<Array<[string, InviteCode]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__inviteCodes(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__inviteCodes(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextAnalysisId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextAnalysisId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextAnalysisId();
            return result;
        }
    }
    async __nextAnnotationId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextAnnotationId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextAnnotationId();
            return result;
        }
    }
    async __nextBookId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextBookId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextBookId();
            return result;
        }
    }
    async __nextChapterId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextChapterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextChapterId();
            return result;
        }
    }
    async __nextChatMessageId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextChatMessageId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextChatMessageId();
            return result;
        }
    }
    async __nextCommentId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextCommentId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextCommentId();
            return result;
        }
    }
    async __nextInviteCodeId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextInviteCodeId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextInviteCodeId();
            return result;
        }
    }
    async __nextRecordingId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextRecordingId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextRecordingId();
            return result;
        }
    }
    async __recordings(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Recording]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__recordings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__recordings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAccess(): Promise<AccessCheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAccess();
                return from_candid_AccessCheckResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAccess();
            return from_candid_AccessCheckResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimInviteCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimInviteCode(arg0);
            return result;
        }
    }
    async clearChat(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChat(arg0);
            return result;
        }
    }
    async createBook(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBook(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBook(arg0, arg1, arg2);
            return result;
        }
    }
    async createChapter(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChapter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChapter(arg0, arg1);
            return result;
        }
    }
    async createComment(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAnalysis(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return result;
        }
    }
    async deleteBook(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async deleteChapter(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deleteRecording(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecording(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecording(arg0);
            return result;
        }
    }
    async generateInviteCode(arg0: bigint, arg1: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAnalysis(arg0: bigint): Promise<Analysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnotation(arg0: bigint): Promise<TextAnnotation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnotation(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnotation(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnotations(arg0: bigint): Promise<Array<TextAnnotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnotations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnotations(arg0);
            return result;
        }
    }
    async getBook(arg0: bigint): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookStats(arg0: bigint): Promise<{
        totalChars: bigint;
        avgWordsPerChapter: bigint;
        chapterCount: bigint;
        totalWords: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookStats(arg0);
            return result;
        }
    }
    async getChapter(arg0: bigint): Promise<Chapter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverallStats(): Promise<{
        totalBooks: bigint;
        totalChapters: bigint;
        totalWords: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverallStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverallStats();
            return result;
        }
    }
    async getRecordingAudio(arg0: bigint): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordingAudio(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordingAudio(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnalysesByBook(arg0: bigint): Promise<Array<Analysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalysesByBook(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalysesByBook(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnalysesByChapter(arg0: bigint): Promise<Array<Analysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalysesByChapter(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalysesByChapter(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnnotationsByAnalysis(arg0: bigint): Promise<Array<TextAnnotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnotationsByAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnotationsByAnalysis(arg0);
            return result;
        }
    }
    async listBooksByOwner(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBooksByOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBooksByOwner();
            return result;
        }
    }
    async listChaptersByBook(arg0: bigint): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChaptersByBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChaptersByBook(arg0);
            return result;
        }
    }
    async listCommentsByChapter(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCommentsByChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCommentsByChapter(arg0);
            return result;
        }
    }
    async listInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInviteCodes();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInviteCodes();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessagesByBook(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessagesByBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessagesByBook(arg0);
            return result;
        }
    }
    async listRecordingsByChapter(arg0: bigint): Promise<Array<{
        id: bigint;
        voice: string;
        createdAt: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecordingsByChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecordingsByChapter(arg0);
            return result;
        }
    }
    async reorderChapters(arg0: bigint, arg1: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderChapters(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderChapters(arg0, arg1);
            return result;
        }
    }
    async revokeInviteCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInviteCode(arg0);
            return result;
        }
    }
    async saveAnalysis(arg0: bigint, arg1: bigint | null, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAnalysis(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAnalysis(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async saveAnnotations(arg0: bigint, arg1: Array<{
        explanation: string;
        color: string;
        text: string;
        proposal: string;
    }>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAnnotations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAnnotations(arg0, arg1);
            return result;
        }
    }
    async saveRecording(arg0: bigint, arg1: bigint, arg2: string, arg3: Uint8Array): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRecording(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRecording(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAnnotationApproved(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnotationApproved(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnotationApproved(arg0, arg1);
            return result;
        }
    }
    async updateBook(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBookMetadata(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookMetadata(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookMetadata(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateChapter(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1, arg2);
            return result;
        }
    }
    async updateChapterIndents(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapterIndents(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapterIndents(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_AccessCheckResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessCheckResult): AccessCheckResult {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Analysis_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Analysis): Analysis {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_InviteCodeStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCodeStatus): InviteCodeStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_InviteCode_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCode): InviteCode {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Analysis]): Analysis | null {
    return value.length === 0 ? null : from_candid_Analysis_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TextAnnotation]): TextAnnotation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Book]): Book | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chapter]): Chapter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InviteCodeStatus;
    expiresAt: [] | [bigint];
    code: string;
    createdAt: bigint;
    usedCount: bigint;
    claimedBy: Array<Principal>;
    maxUses: bigint;
}): {
    status: InviteCodeStatus;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    usedCount: bigint;
    claimedBy: Array<Principal>;
    maxUses: bigint;
} {
    return {
        status: from_candid_InviteCodeStatus_n12(_uploadFile, _downloadFile, value.status),
        expiresAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        createdAt: value.createdAt,
        usedCount: value.usedCount,
        claimedBy: value.claimedBy,
        maxUses: value.maxUses
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    provider: string;
    analysisType: string;
    createdAt: bigint;
    bookId: bigint;
    chapterId: [] | [bigint];
    resultContent: string;
}): {
    id: bigint;
    provider: string;
    analysisType: string;
    createdAt: bigint;
    bookId: bigint;
    chapterId?: bigint;
    resultContent: string;
} {
    return {
        id: value.id,
        provider: value.provider,
        analysisType: value.analysisType,
        createdAt: value.createdAt,
        bookId: value.bookId,
        chapterId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.chapterId)),
        resultContent: value.resultContent
    };
}
function from_candid_tuple_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Analysis]): [bigint, Analysis] {
    return [
        value[0],
        from_candid_Analysis_n4(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _InviteCode]): [string, InviteCode] {
    return [
        value[0],
        from_candid_InviteCode_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    revoked: null;
} | {
    exhausted: null;
}): InviteCodeStatus {
    return "active" in value ? InviteCodeStatus.active : "revoked" in value ? InviteCodeStatus.revoked : "exhausted" in value ? InviteCodeStatus.exhausted : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ExistingUser: null;
} | {
    Admin: null;
} | {
    NewUserNeedsCode: null;
}): AccessCheckResult {
    return "ExistingUser" in value ? AccessCheckResult.ExistingUser : "Admin" in value ? AccessCheckResult.Admin : "NewUserNeedsCode" in value ? AccessCheckResult.NewUserNeedsCode : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Analysis]>): Array<[bigint, Analysis]> {
    return value.map((x)=>from_candid_tuple_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Analysis>): Array<Analysis> {
    return value.map((x)=>from_candid_Analysis_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InviteCode>): Array<InviteCode> {
    return value.map((x)=>from_candid_InviteCode_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _InviteCode]>): Array<[string, InviteCode]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
